Start training ...
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "/data_a11/mayi/project/wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
  File "/data_a11/mayi/project/wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 228, in <module>
        fire.Fire(train)fire.Fire(train)

  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
        component_trace = _Fire(component, args, parsed_flag_args, context, name)component_trace = _Fire(component, args, parsed_flag_args, context, name)

  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
        component, remaining_args = _CallAndUpdateTrace(component, remaining_args = _CallAndUpdateTrace(

  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
        component = fn(*varargs, **kwargs)component = fn(*varargs, **kwargs)

  File "/data_a11/mayi/project/wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 51, in train
  File "/data_a11/mayi/project/wespeaker/examples/voxceleb/v2/wespeaker/bin/train.py", line 51, in train
        dist.init_process_group(backend='nccl')dist.init_process_group(backend='nccl')

  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 583, in init_process_group
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 583, in init_process_group
        default_pg = _new_process_group_helper(default_pg = _new_process_group_helper(

  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 708, in _new_process_group_helper
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 708, in _new_process_group_helper
        raise RuntimeError("Distributed package doesn't have NCCL " "built in")raise RuntimeError("Distributed package doesn't have NCCL " "built in")

RuntimeErrorRuntimeError: : Distributed package doesn't have NCCL built inDistributed package doesn't have NCCL built in

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2232569) of binary: /home/mayi/anaconda3/envs/wespeaker/bin/python
Traceback (most recent call last):
  File "/home/mayi/anaconda3/envs/wespeaker/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.1', 'console_scripts', 'torchrun')())
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/mayi/anaconda3/envs/wespeaker/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
wespeaker/bin/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-11-01_13:31:35
  host      : hlt04
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2232570)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-01_13:31:35
  host      : hlt04
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2232569)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
